CREATE DATABASE ANTVDA

USE ANTVDA;

CREATE TABLE Departamento
(Id INT, PRIMARY KEY IDENTITY (1,1),
Nome VARCHAR (200) NOT NULL, UNIQUE
DataCriacao DATE,
Email VARCHAR (200) UNIQUE,
Remover INT
);